spring:
  cache:
    type: redis
    redis:
      time-to-live: PT1H
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/job-offers
      auto-index-creation: true
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:postgresql://localhost:9999/job-offers-users
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: true
  task:
    scheduling:
      enable: true

job-offers:
  offer:
    fetcher:
      port: 5057
      uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
    rest-template-config:
      connection-time-out: 5000
      read-time-out: 5000
    scheduler:
      fixed-rate: PT1H
      enable: true
  user:
    auth:
      jwt:
        expirationTimeInMs: 1209600000
        secret: test
        issuer: job-offers-backend
